language: node_js
node_js:
  - "8.11.4"
cache: yarn
branches:
  only:
    - dev
    - master
before_script:
  - yarn test:coverage && cat test-coverage/lcov.info | node_modules/.bin/coveralls
script:
  - yarn build
  - yarn release
notifications:
  email:
    - dev-notifications@noblockno.party
